// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID            pgtype.UUID
	RoomID        pgtype.UUID
	Message       string
	ReactionCount int64
	Answered      bool
}

type Room struct {
	ID    pgtype.UUID
	Theme string
}
